### ISSUE TITLE
[BUG] Can't install native expo project dependencies

### ISSUE THREAD

**Issue by nicolinho22** [callstack/reassure-examples#17]
**Describe the bug**
When running `npm install` in the native expo project, a "unable to resolve dependency tree" error appears, blocking me from installing the dependencies. This also happens when I try to install reassure dependencies in my own project.

**To Reproduce**
1. Go to examples/native-expo in your terminal
2. Run npm install
3. See error

**Expected behavior**
Dependencies install successfully

**Screenshots**
<img width="744" alt="Screenshot 2023-05-10 at 11 45 41" src="https://github.com/callstack/reassure-examples/assets/40872253/476ef9c4-d31a-4756-96d2-9a4c4b809240">

**Desktop (please complete the following information):**
 - OS: macOS 13.0.1
- NPM version 16.13.0

**Comment by mdjastrzebski** [comment]
I'll check with NPM, but it definitely should work with `yarn`. So you might use it as quick workaround.

**Comment by nicolinho22** [comment]
@mdjastrzebski got it to work with npm with solution you provided in https://github.com/callstack/react-native-testing-library/issues/1409 :)
